# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#================================#
#=== Raspberry Pi Cooling Fan ===#
#================================#
sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°F"
    value_template: "{{ value | multiply(0.001) | round(2) }}"
    scan_interval: 10
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: disk_use_percent
      - type: memory_use_percent
      - type: processor_use
      - type: swap_use_percent
      - type: last_boot

switch:
  - platform: rpi_gpio
    ports:
      13: RPI Cooling Fan

climate:
  - platform: generic_thermostat
    name: RPI Cooling Fan Controller
    heater: switch.rpi_cooling_fan
    target_sensor: sensor.cpu_temperature
    min_temp: 45
    max_temp: 75
    ac_mode: true
    target_temp: 40
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 5
    initial_hvac_mode: "cool"
